patroni:
  hosts:
    # Control nodes
    patroni1:
      ansible_host: 192.168.1.183
    patroni2:
      ansible_host: 192.168.1.243
    patroni3:
      ansible_host: 192.168.1.244
   
#k8s_workers:
#  hosts:
    # Worker nodes
#    ws1.kryukov.local:
#      ansible_host: 192.168.1.186
  #  ws2.kryukov.local:
  #    ansible_host: 192.168.218.175
  #  ws3.kryukov.local:
  #    ansible_host: 192.168.218.176
  #  ws4.kryukov.local:
  #    ansible_host: 192.168.218.177
  
patroni_cluster:
  children:
    patroni:
 #   k8s_workers:
