# Холст для всяких тестов.
---
 
- name: Test playbook
  hosts: patroni_cluster
  #become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  #####################################################  
  #- name: Gather the package facts
  #  package_facts:
  #    manager: auto

  #- name: Print all available packages
  #  debug:
  #    var: ansible_facts.packages
########################################################
 
#  - name: "update hostnames"
#    hostname:
#      name: "{{ item }}"
#    loop:
#      - centos02

#  - name: "update hostnames"
#    hostname:
#      name: "{{ item }}"
#    loop:
#      - centos03      


  #- name: Show Value of Variable
  #  debug:
      #msg: "{{ groups['patroni_cluster'][1] }}"
  #    msg: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  
  #- name: "update hostnames1"
  #  debug:
  #    msg: "{{ groups['patroni_cluster'][0] }}"
  #  when: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address'][0] }}"

  #- name: "update hostnames2"
  #  debug:
  #    msg: "{{ groups['patroni_cluster'][1] }}"
  #  when: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address'][1] }}"

  #- name: "update hostnames3"
  #  debug:
  #    msg: "{{ groups['patroni_cluster'][2] }}"
  #  when: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address'][2] }}"




  #- name: Run a shell command and register its output as a variable
  #  shell: ls -latr
  #  register: command_result
  #- name: Set variable
  #  set_fact:
  #    my_current_value: "{{ command_result.stdout }}"
  #- name: Show Value of Variable
  #  debug:
  #    msg: "{{ my_current_value }}"
############################################





  

