# Холст для всяких тестов.
---
 vars:
      list1:
        - name: name1
          value1: matvey
        - name: name2
          value1: misha
      list2:
        - name: name1
          value2: sergey
        - name: name3
          value2: andrey
          
- name: Test playbook
  hosts: patroni_cluster
  #become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
   
  - name: this debug 
    debug:
      msg: "{{ list1 | community.general.lists_mergeby(list2, 'name') }}"    
  #- name: chown mknod
  #  shell: chown postgres /dev/watchdog
  #  register: contents

  #- name: Init PostgreSQL DB
  #  debug:
  #    msg: "{{ chown_contents }}"
 
  #####################################################  
  #- name: Gather the package facts
  #  package_facts:
  #    manager: auto

  #- name: Print all available packages
  #  debug:
  #    var: ansible_facts.packages
########################################################
    

#  - name: "update hostnames"
#    hostname:
#      name: "{{ item }}"
#    loop:
#      - centos02

#  - name: "update hostnames"
#    hostname:
#      name: "{{ item }}"
#    loop:
#      - centos03      


  #- name: Show Value of Variable
  #  debug:
  #    msg: "{{ groups['patroni_cluster'][1] }}"

  
  #- name: Run a shell command and register its output as a variable
  #  shell: ls -latr
  #  register: command_result
  #- name: Set variable
  #  set_fact:
  #    my_current_value: "{{ command_result.stdout }}"
  #- name: Show Value of Variable
  #  debug:
  #    msg: "{{ my_current_value }}"
############################################





  

